server {
    listen 8090;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /manifest.webmanifest {
        default_type application/manifest+json;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:30334/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 0;
        proxy_request_buffering off;
    }

    location /nasapi/ {
        proxy_pass http://127.0.0.1:9190/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
